import PrimeVue from 'primevue/config';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';
import 'primevue/resources/themes/lara-light-blue/theme.css';
import ToastService from 'primevue/toastservice';
import ConfirmationService from 'primevue/confirmationservice';
import Tooltip from 'primevue/tooltip';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ContextMenu from 'primevue/contextmenu';
import Panel from 'primevue/panel';
import MultiSelect from 'primevue/multiselect';
import Tag from 'primevue/tag';
import Chip from 'primevue/chip';
import Dialog from 'primevue/dialog';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import InputNumber from 'primevue/inputnumber';
import Checkbox from 'primevue/checkbox';
import FileUpload from 'primevue/fileupload';
import Toast from 'primevue/toast';
import ConfirmDialog from 'primevue/confirmdialog';
import TabMenu from 'primevue/tabmenu';
import Chart from 'primevue/chart';
import Ripple from 'primevue/ripple';

export function installPrimeVue(app) {
    app.use(PrimeVue);
    app.use(ToastService);
    app.use(ConfirmationService);
    app.directive('tooltip', Tooltip);
    app.directive('ripple', Ripple);
    app.component('DataTable', DataTable);
    app.component('Column', Column);
    app.component('ContextMenu', ContextMenu);
    app.component('Panel', Panel);
    app.component('MultiSelect', MultiSelect);
    app.component('Tag', Tag);
    app.component('Chip', Chip);
    app.component('Dialog', Dialog);
    app.component('Button', Button);
    app.component('InputText', InputText);
    app.component('Textarea', Textarea);
    app.component('InputNumber', InputNumber);
    app.component('Checkbox', Checkbox);
    app.component('FileUpload', FileUpload);
    app.component('ConfirmDialog', ConfirmDialog);
    app.component('Toast', Toast);
    app.component('TabMenu', TabMenu);
    app.component('Chart', Chart);
}
